language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - curl -sL cpanmin.us | perl - https://github.com/andrewalker/p5-webservice-digitalocean.git

branches:
  only:
    - master